# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2020-09-22 17:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200922_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 17, 19, 34, 536877, tzinfo=utc)),
        ),
    ]
